apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hossamzwein/final-project-backend
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: final-configmap
                  key: user
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: final-configmap
                  key: database
          envFrom:
            - secretRef:
                name: mysql-secret